Repository ipproyectosysoluciones/Reserva-Hotel-App, pull requests merged in 2023-08, with the labels that each got.

#26 Dev front
  client/src/App.jsx
  client/src/components/card/Card.jsx
  client/src/redux/actions/actions.js
  client/src/redux/actions/bedroomsActions.js
  client/src/redux/actions/bookingActions.js
  client/src/redux/actions/notificationActions.js
  client/src/redux/actions/plansActions.js
  client/src/redux/actions/travelActions.js
  client/src/redux/actions/userActions.js
  client/src/store/featureSlice.js
  client/src/store/store.js
  client/src/utils/api.js
  client/src/utils/helpers.js
  client/src/views/Landing.jsx
Labels: enhancement

#24 Dev back
  server/index.js
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/config/db.js
  server/src/controllers/administratorasControllers.js
  server/src/controllers/bedroomControllers.js
  server/src/controllers/bookingControllers.js
  server/src/controllers/categoriesControllers.js
  server/src/controllers/diaryControllers.js
  server/src/controllers/sendMaILController.js
  server/src/controllers/testimonialsControllers.js
  server/src/controllers/travelControllers.js
  server/src/controllers/usersControllers.js
  server/src/routes/bookingRoutes.js
  server/src/routes/categoriasRoutes.js
  server/src/routes/index.js
  server/src/routes/notifications.js
  server/src/routes/plan.js
  server/src/routes/restaurant.js
  server/src/routes/testimonialsRoutes.js
  server/src/routes/travel.js
  server/src/routes/users.js
  server/src/views/index.ejs
Labels: enhancement

#27 Dev front
  client/package-lock.json
  client/package.json
  client/src/assets/images/image.png
  client/src/components/NavBar/NavBar.jsx
  client/src/components/NavBar/assets/Logo.jpg
  client/src/views/Detail.jsx
  client/src/views/Landing.jsx
Labels: enhancement

#32 Vistas en backend de Usuarios y Recorrido al 80%
  server/package-lock.json
  server/package.json
  server/src/controllers/administratorasControllers.js
  server/src/controllers/bedroomControllers.js
  server/src/controllers/sendMaILController.js
  server/src/models/Administrators.js
  server/src/partials/footer.ejs
  server/src/partials/head.ejs
  server/src/partials/header.ejs
  server/src/partials/menu.ejs
  server/src/partials/scripts.ejs
  server/src/routes/adminRoutes.js
  server/src/routes/bedroomRoutes.js
  server/src/routes/homeRoutes.js
  server/src/routes/index.js
  server/src/routes/travel.js
  server/src/routes/users.js
  server/src/views/index.ejs
  server/src/views/pages/admin/admin-create.ejs
  server/src/views/pages/admin/admin-get.ejs
  server/src/views/pages/admin/admin-update.ejs
  server/src/views/pages/administrators.ejs
  server/src/views/pages/travel.ejs
  server/src/views/pages/users.ejs
Labels: enhancement

#35 Revisar
  client/src/assets/plans.json
  client/src/components/Banner/Banner.jsx
  client/src/components/CardAmenitie/CardAmenitie.jsx
  client/src/components/CardsAmenitie/CardsAmenitie.jsx
  client/src/components/CardsPlan/CardsPlan.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Item.jsx
  client/src/components/Footer/ItemsContainers.jsx
  client/src/components/Footer/Menus.js
  client/src/components/Footer/SocialIcon.jsx
  client/src/components/album/album.jsx
  client/src/components/login/Login.jsx
  client/src/views/Contacto.jsx
  client/src/views/Detail.jsx
  client/src/views/Landing.jsx
  server/src/routes/bedroomRoutes.js
Labels: documentation, enhancement

#36 Dev back
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/controllers/bannerControllers.js
  server/src/controllers/bedroomControllers.js
  server/src/models/Bedrooms.js
  server/src/models/Travel.js
  server/src/routes/bannerRoutes.js
  server/src/routes/bedroomRoutes.js
  server/src/routes/plan.js
  server/src/routes/testimonialsRoutes.js
  server/src/views/pages/banner.ejs
  server/src/views/pages/bedrooms.ejs
  server/src/views/pages/plans.ejs
  server/src/views/pages/testimonials.ejs
  server/src/views/pages/travel.ejs
  server/src/views/partials/menu.ejs
  server/uploads/26d7dc26654e77801079c1440056db16
  server/uploads/542182d957cdaf931a847202f90f4dce
  server/uploads/6e3cb7de5f531c91d54cebe28d9abeaf
  server/uploads/7183bb3977633a83a88c8e56c383b798
  server/uploads/9bfae91dd473e26616f5f481f95fe934
  server/uploads/9d4844fb72f1c1ddb183d9635c2ccc51
  server/uploads/f1c9a15f0bcede004e7e3f5c374dc275
Labels: enhancement

#40 Dev-demo -> Dev-front
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/controllers/bannerControllers.js
  server/src/controllers/bedroomControllers.js
  server/src/models/Bedrooms.js
  server/src/models/Travel.js
  server/src/routes/bannerRoutes.js
  server/src/routes/bedroomRoutes.js
  server/src/routes/plan.js
  server/src/routes/testimonialsRoutes.js
  server/src/views/pages/banner.ejs
  server/src/views/pages/bedrooms.ejs
  server/src/views/pages/plans.ejs
  server/src/views/pages/testimonials.ejs
  server/src/views/pages/travel.ejs
  server/src/views/partials/menu.ejs
  server/uploads/26d7dc26654e77801079c1440056db16
  server/uploads/542182d957cdaf931a847202f90f4dce
  server/uploads/6e3cb7de5f531c91d54cebe28d9abeaf
  server/uploads/7183bb3977633a83a88c8e56c383b798
  server/uploads/9bfae91dd473e26616f5f481f95fe934
  server/uploads/9d4844fb72f1c1ddb183d9635c2ccc51
  server/uploads/f1c9a15f0bcede004e7e3f5c374dc275
Labels: bug

#37 Dev front
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/PageNotFound/PageNotFound.jsx
  client/src/assets/bedrooms.json
  client/src/assets/hall/1.jpg
  client/src/assets/hall/2.jpg
  client/src/assets/hall/3.jpg
  client/src/assets/images/Error404.png
  client/src/assets/images/loading.gif
  client/src/assets/plans.json
  client/src/assets/urlCloudinary.txt
  client/src/components/Banner/Banner.jsx
  client/src/components/CardBedroom/CardBedroom.jsx
  client/src/components/CardsBedroom/CardsBedroom.jsx
  client/src/components/FormDisponibilidad/FormDisponibilidad.jsx
  client/src/components/album/album.jsx
  client/src/components/bedroomPreview/preview1.jsx
  client/src/components/bedroomPreview/preview2.jsx
  client/src/components/login/Login.jsx
  client/src/redux/actions/userActions.js
  client/src/redux/features/bookingSlice.js
  client/src/redux/features/userSlice.js
  client/src/views/Detail.jsx
  client/src/views/Landing.jsx
  client/tailwind.config.js
  client/vite.config.js.timestamp-1692845830513-87ba84c164118.mjs
Labels: enhancement

#39 Dev back (#36) (#38)
  server/src/controllers/bedroomControllers.js
  server/src/controllers/bookingControllers.js
  server/src/models/Bedrooms.js
  server/src/routes/bedroomRoutes.js
  server/src/routes/bookingRoutes.js
  server/src/views/pages/bedrooms.ejs
Labels: enhancement

#46 Dev-demo -> Dev-front
  server/src/controllers/bedroomControllers.js
  server/src/controllers/bookingControllers.js
  server/src/models/Bedrooms.js
  server/src/routes/bedroomRoutes.js
  server/src/routes/bookingRoutes.js
  server/src/views/pages/bedrooms.ejs
Labels: enhancement

#45 Revisar (#44)
  server/src/app.js
  server/src/public/uploads/26d7dc26654e77801079c1440056db16
  server/src/public/uploads/542182d957cdaf931a847202f90f4dce
  server/src/public/uploads/6e3cb7de5f531c91d54cebe28d9abeaf
  server/src/public/uploads/7183bb3977633a83a88c8e56c383b798
  server/src/public/uploads/9bfae91dd473e26616f5f481f95fe934
  server/src/public/uploads/9d4844fb72f1c1ddb183d9635c2ccc51
  server/src/public/uploads/f1c9a15f0bcede004e7e3f5c374dc275
Labels: enhancement

#42 Delete package,json
  package.json
Labels: bug

#43 Delete package-lock.json
  package-lock.json
Labels: bug

#47 Dev front
  client/src/components/Banner/Banner.jsx
  client/src/components/CardBedroom/CardBedroom.jsx
  client/src/components/CardsBedroom/CardsBedroom.jsx
Labels: enhancement

#49 Dev back
  server/src/app.js
Labels: enhancement

#67 Dev-demo -> Dev-back (#65)
  server/src/models/Travel.js
  server/src/routes/bookingRoutes.js
  server/src/routes/index.js
  server/src/routes/restaurant.js
  server/src/routes/travel.js
  server/src/views/pages/restaurant.ejs
  server/src/views/pages/travel.ejs
Labels: enhancement

#93 Dev front
  client/src/components/Banner/Banner.jsx
  client/src/components/CardsPlan/CardsPlan.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/views/Landing.jsx
Labels: documentation

#104 Revisar y Aprobar
  client/src/components/Banner/Banner.jsx
  client/src/components/CardsPlan/CardsPlan.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/views/Landing.jsx
Labels: documentation

#105 Revisar y Aprobar
  server/package.json
Labels: documentation

#106 Revisar y Aprobar
  server/package.json
Labels: documentation

#107 Dev back
  client/src/components/login/Login.jsx
  server/index.js
  server/src/config/db.js
  server/src/controllers/bedroomControllers.js
  server/src/controllers/bookingControllers.js
  server/src/controllers/categoriesControllers.js
  server/src/controllers/planControllers.js
  server/src/models/Categories.js
  server/src/models/Users.js
  server/src/routes/adminRoutes.js
  server/src/routes/bannerRoutes.js
  server/src/routes/bedroomRoutes.js
  server/src/routes/bookingRoutes.js
  server/src/routes/categoriasRoutes.js
  server/src/routes/index.js
  server/src/routes/notifications.js
  server/src/routes/plan.js
  server/src/routes/restaurant.js
  server/src/routes/travel.js
  server/src/routes/users.js
  server/src/views/pages/bedrooms.ejs
  server/src/views/pages/categories.ejs
  server/src/views/pages/plans.ejs
  server/src/views/partials/menu.ejs
Labels: documentation

#110 Dev back
  client/src/components/login/Login.jsx
  server/index.js
  server/src/config/db.js
  server/src/controllers/bedroomControllers.js
  server/src/controllers/bookingControllers.js
  server/src/controllers/categoriesControllers.js
  server/src/controllers/planControllers.js
  server/src/models/Categories.js
  server/src/models/Users.js
  server/src/routes/adminRoutes.js
  server/src/routes/bannerRoutes.js
  server/src/routes/bedroomRoutes.js
  server/src/routes/bookingRoutes.js
  server/src/routes/categoriasRoutes.js
  server/src/routes/index.js
  server/src/routes/notifications.js
  server/src/routes/plan.js
  server/src/routes/restaurant.js
  server/src/routes/travel.js
  server/src/routes/users.js
  server/src/views/pages/bedrooms.ejs
  server/src/views/pages/categories.ejs
  server/src/views/pages/plans.ejs
  server/src/views/partials/menu.ejs
Labels: documentation

#114 Dev-front -> Dev-back (#112)
  server/src/config/db.js
  server/src/controllers/bookingControllers.js
  server/src/controllers/usersControllers.js
  server/src/routes/bedroomRoutes.js
  server/src/routes/bookingRoutes.js
  server/src/views/pages/bookings.ejs
  server/src/views/pages/categories.ejs
  server/src/views/pages/users.ejs
Labels: documentation

#113 Dev-front -> main
  server/src/config/db.js
  server/src/controllers/bookingControllers.js
  server/src/controllers/usersControllers.js
  server/src/routes/bedroomRoutes.js
  server/src/routes/bookingRoutes.js
  server/src/views/pages/bookings.ejs
  server/src/views/pages/categories.ejs
  server/src/views/pages/users.ejs
Labels: documentation

#117 Bug fixes
  server/src/config/db.js
  server/src/controllers/bookingControllers.js
Labels: documentation

#119 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation

#125 Bug fixes
  client/src/components/login/Login.jsx
  server/src/routes/bedroomRoutes.js
Labels: documentation

#126 Dev back
  server/src/routes/plan.js
  server/src/views/pages/plans.ejs
Labels: bug

#128 Dev back
  server/src/routes/plan.js
Labels: bug

#129 Dev back
  server/src/routes/bedroomRoutes.js
Labels: bug

#130 Dev-front -> Dev-back
  client/src/App.jsx
  client/src/assets/bookings.json
  client/src/components/CardsBedroom/CardsBedroom.jsx
  client/src/components/Filtros/Filtros.jsx
  client/src/components/bedroomPreview/preview1.jsx
  client/src/components/bedroomPreview/preview2.jsx
  client/src/components/login/Login.jsx
  client/src/views/Landing.jsx
  server/src/routes/plan.js
Labels: documentation

#133 Update app.jsx
  client/src/App.jsx
Labels: documentation

#138 Dev back
  server/src/routes/plan.js
Labels: documentation

#141 Dev back
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/CardBedroom/CardBedroom.jsx
  client/src/components/CardsBedroom/CardsBedroom.jsx
  client/src/components/CardsPlan/CardsPlan.jsx
  server/src/routes/plan.js
Labels: documentation

#142 Bug fixes
  server/src/views/pages/plans.ejs
Labels: documentation

#143 Troubleshooting in Cors
  server/src/app.js
Labels: documentation

#144 Troubleshooting in SessionStore
  server/src/app.js
Labels: documentation

#145 Update process dashboard
  server/src/helpers/bedrooms.js
Labels: documentation

#146 Update
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/CardBedroom/CardBedroom.jsx
  client/src/components/CardsBedroom/CardsBedroom.jsx
  client/src/components/CardsPlan/CardsPlan.jsx
  client/src/redux/actions/bedroomsActions.js
  client/src/redux/actions/plansActions.js
  client/src/redux/features/bedroomsSlice.js
  client/src/redux/features/userSlice.js
  server/src/routes/bedroomRoutes.js
  server/src/routes/plan.js
Labels: documentation

#147 Dev back
  server/src/routes/adminRoutes.js
  server/src/routes/bannerRoutes.js
  server/src/routes/bedroomRoutes.js
  server/src/routes/bookingRoutes.js
  server/src/routes/categoriasRoutes.js
  server/src/routes/plan.js
  server/src/routes/restaurant.js
  server/src/routes/testimonialsRoutes.js
  server/src/routes/travel.js
  server/src/routes/users.js
Labels: documentation

#149 Dev back
  client/src/App.jsx
  client/src/assets/bedrooms.json
  client/src/components/CardsPlan/CardsPlan.jsx
  client/src/views/Landing.jsx
  server/src/controllers/usersControllers.js
  server/src/models/Users.js
  server/src/routes/users.js
Labels: documentation
